name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v

      - name: Build V
        run: cd v && make && sudo ./v symlink && cd -

      - name: V doctor
        run: v doctor

      - name: Ensure everything is formatted
        run: cd coreutils && make testfmt

      - name: Build all
        run: cd coreutils && v run build.vsh

      - name: Build all with -prod
        run: cd coreutils && v run build.vsh -prod

      - name: Native utils diagnostics (before GNU coreutils)
        run: |
          sleep --version
          uptime --version
      - name: Checkout Coreutils (for tests)
        uses: actions/checkout@v2
        with:
          path: coreutils
      - name: Setup the original GNU coreutils for comparison
        uses: ShenTengTu/setup-gnu-coreutils-action@v1
      - name: Test GNU coreutils uptime
        run: uptime --version

      - name: Run tests
        run: cd coreutils && make test
