name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v
    - name: Checkout Coreutils
      uses: actions/checkout@v2
      with:
        path: coreutils
    - name: Build V
      run: |
        cd v
        make
        sudo ./v symlink
        cd -
    - name: V doctor
      run: v doctor

    - name: Ensure everything is formatted
      run: cd coreutils && make testfmt

    - name: Run tests
      run: cd coreutils && make test

    - name: Build all
      run: cd coreutils && v run build.vsh

    - name: Build all with -prod
      run: cd coreutils && v run build.vsh -prod
