name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout Coreutils
      uses: actions/checkout@v2
      with:
        path: coreutils
    - name: Build V
      run: |
        make
        sudo ./v symlink
        cd coreutils/
    - name: V doctor
      run: v doctor
    - name: Run tests
      run: v test .
    - name: Build all coreutils
      run: v run build.vsh
    - name: Build all coreutils with -prod
      run: v run build.vsh -prod
