name: Build and Test Manual

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  winos-test:
    runs-on: windows-latest
    env:
      VFLAGS: -cc tcc
      VJOBS: 1
      VTEST_SHOW_START: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: coreutils
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: Build V
        shell: bash
        run: |
          # Build V
          cd v && ./make.bat -tcc
          echo "adding '${PWD}' to PATH"
          echo "${PWD}" >> $GITHUB_PATH
      - name: V doctor
        shell: bash
        run: |
          # V doctor
          v doctor          
      # - name: Download uutils/coreutils
      #   uses: engineerd/configurator@v0.0.8
      #   with:
      #     name: 'coreutils.exe'
      #     url: 'https://github.com/uutils/coreutils/releases/download/0.0.17/coreutils-0.0.17-x86_64-pc-windows-msvc.zip'
      #     pathInArchive: 'coreutils-0.0.17-x86_64-pc-windows-msvc/coreutils.exe'
      - name: Info
        shell: bash
        run: |
          ## Info
          # environment
          echo "## environment"
          echo "CI='${CI}'"
          # tooling info display
          echo "## testing/tooling"
          # coreutils
          which tcc >/dev/null 2>&1 && (tcc --version | head -1) || true
          v --version
      - name: Build all
        shell: bash
        run: |
          # Build all
          cd coreutils && v build.vsh
      - name: Run tests
        shell: bash
        run: |
          # Run tests
          cd coreutils && v test .

